#!/bin/sh

echo "running ltsp-setup ..."

echo " >> enable and start ltsp-update.service"
systemctl enable  ltsp-update.service
systemctl start ltsp-update.service

echo " >> configure pam_mkhomedir"
#pam_mkhomedir
pam-auth-update --package --enable mkhomedir

echo " >> configure dconf"
#no updates
cat <<EOF > /etc/dconf/db/local.d/10-no-autoupdates
[org/gnome/software]
allow-updates=false
download-updates=false
download-updates-notify=false
EOF

dconf update

echo " >> disable ltsp-setup.service"
systemctl disable ltsp-setup.service

echo "done"

exit 0
