#!/bin/sh

CONFIG="/home/.config"
mkdir -p $CONFIG/login

#configure wlan
if nm-online -s -q;then
    if test -f $CONFIG/wlan;then
	. $CONFIG/wlan
	if nmcli radio wifi on;then
	    nmcli device wifi connect $SSID password $PASSWORD
	    sleep 2
	fi
    fi
fi

#update config from server
if nm-online -q -t 3600; then
    SERVER=$(ltsp-find)
    if test "$SERVER" != ""; then
	echo "SERVER=$SERVER" > $CONFIG/server
	TMP=$(mktemp)
	if wget -O $TMP http://$SERVER:8000/config.tgz; then
	    tar -xzf $TMP -C $CONFIG
	    /lib/live/config/0028-ltsp-pwmerge
	fi
	rm $TMP
    fi    
fi

