#!/bin/sh

echo -n "running ltsp-allinone-init ..."

. /home/.config/hosttype

if test "$HOSTTYPE" = "laptop";then
    echo "laptop"
    /usr/local/lib/ltsp/laptop-update
else
    echo "server"
fi


exit 0
