#!/bin/sh

#. /lib/live/config.sh

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline(){
    if grep -q ltsp-server /proc/cmdline ;then
	
	touch /var/lib/live/config/ltsp-setup
	exit 0
	
    fi
}

Init ()
{
        #check if allready done
        if test -f /var/lib/live/config/ltsp-setup -o -f /etc/ltsp/ltsp.conf
	then
		exit 0
	fi

	echo -n " ltlsp-setup ..."
}

Config ()
{

	systemctl enable ltsp-setup.service 
        
	# Creating state file
	touch /var/lib/live/config/ltsp-setup
	
	echo "done"
}

Cmdline
Init
Config
