#!/bin/sh

#set -e

Config (){
    CONFIG="/home/.config"
    if test -f $CONFIG/login/passwd; then
	TMP1=$(mktemp -d)
	TMP2=$(mktemp -d)
	
	if /usr/local/sbin/pwfilter /etc $TMP2; then
	    /usr/local/sbin/pwmerge $CONFIG/login $TMP2 $TMP1
	    cp -a $TMP1/* /etc
	    
	    #prevent running these ...
	    #touch /var/lib/live/config/live-debconfig_passwd
	    touch /var/lib/live/config/user-setup
	    #touch /var/lib/live/config/sudo
	else
	    echo "error: cloud not filter"
	fi
      
	rm -r $TMP1
	rm -r $TMP2
    fi
}

Config
