#!/bin/sh

SERVER="192.168.1.122"
PORT=8000

CONFIG="/home/.config"

if nm-online -q -t 3600; then
    if ping -c1 $SERVER 2>&1 >/dev/null; then
	mkdir $CONFIG
	TMP=$(mktemp)
	if wget -O $TMP http://$SERVER:$PORT/config.tgz; then
	    tar -xzf $TMP -C $CONFIG
	    rm $TMP
	fi
    fi
fi
