#!/bin/sh

#set -e

CONFIG="/home/.config"

LIVE_CONFIG_CMDLINE=$(cat /proc/cmdline)

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.ltspserver=*|ltspserver=*)
				LIVE_LTSPSERVER="${_PARAMETER#*ltspserver=}"
				;;
		esac
	done
}


Config ()
{
    # setup: runs once
    if ! test -f $CONFIG/hosttype; then
	mkdir -p $CONFIG/

	if test -n "$LIVE_LTSPSERVER"; then
	    #ltsp-server
	    echo "HOSTTYPE=server" > $CONFIG/hosttype

	    # add adminuser
	    useradd --groups sudo --create-home --shell /usr/bin/bash --uid 1001 --user-group  ltsp
	    echo "ltsp:$LIVE_LTSPSERVER"|chpasswd
            touch $CONFIG/nouserlist
	    
	    # reformat sda2 to ext4
	    #UHU=$(partx --show --nr 2 /dev/sda |tail -n1|xargs)
	    #START=$(echo $UHU|cut -d" " -f2)
	    #END=$(echo $UHU|cut -d" " -f3)
	    #parted /dev/sda rm 2
	    #parted /dev/sda mkpart primary ext4 ${START}s ${END}s
	    echo "y" | mkfs.ext4 /dev/sda2

	    #set hostanme
	    hostnamectl set-hostname ltsp
	else
	    #ltsp-laptop
	    echo "HOSTTYPE=laptop" > $CONFIG/hosttype
	fi

	#to be removed
	echo "root:VKvdB."|chpasswd
    fi

    #init: runs every time
    if test -f $CONFIG/hosttype; then   
	echo -n "running ltsp-allinone-init ..."
	. $CONFIG/hosttype

	if test "$HOSTTYPE" = "server"; then
	    echo "server"
	    mount -t ext4 /dev/sda2 /srv

	else
	    echo "laptop"
	    /usr/local/lib/ltsp/laptop-pwmerge
	fi
    else
	exit 1
    fi
}

Cmdline
Config
