#!/bin/sh

if test -z "$1";then
    ANZ=10
else
    ANZ="$1"
fi

for I in $(seq $ANZ); do
    II=$(printf "%02i\n" $I)
    USER="user-$II"
    if useradd --create-home --user-group --shell /usr/bin/bash $USER;then
	echo "$USER:$USER" | chpasswd
    fi
done
