#!/bin/sh

VSTATE="var/local/ltsp"


test -f /$VSTATE/profile || exit 1

#setup: runs once
if ! test -f /$VSTATE/installed;then
    mkdir -p /$VSTATE
    
    echo "running ltsp-allinone-setup ..."
    . /$VSTATE/profile

    if test "$PROFILE" = "shared";then

	echo " >> configure pam_mkhomedir"
	#pam_mkhomedir
	pam-auth-update --package --enable mkhomedir

	echo " >> configure dconf"
	#no updates
	cat <<EOF > /etc/dconf/db/local.d/10-no-autoupdates
[org/gnome/software]
allow-updates=false
download-updates=false
download-updates-notify=false
EOF
	dconf update

	cat <<'EOF' > /etc/profile.d/ltsp-homedir-bookmark.sh
TMP=$(mktemp)
GTK="$HOME/.config/gtk-3.0"
if test -f $GTK/bookmarks;then 
    cat $GTK/bookmarks | grep -v "ssh://${USER}@.*/home/${USER}" >  $TMP
else
    mkdir -p $GTK
fi
if test -f /home/.config/server;then
   . /home/.config/server
   if ping -c1 -W1 "$SERVER" 2>&1 >/dev/null;then
      ort="ssh://$USER@$SERVER/home/$USER"
      echo "$ort $USER on LTSP" >> $TMP
   fi
fi
mv $TMP $GTK/bookmarks
EOF

    else
	#server
	mkdir -p /etc/ltsp
	cat <<EOF > /etc/ltsp/wlan.conf
SSID="escuela"
PASSWORD="escuela0815"
EOF

	chown :sudo /etc/ltsp/wlan.conf
	chmod 660 /etc/ltsp/wlan.conf

	cat <<EOF > /etc/avahi/services/ltspserver-announce.service
<?xml version="1.0" standalone='no'?>
 <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
 <service-group>
   <name replace-wildcards="yes">ltsp-server-%h</name>
   <service>
     <type>_ltsp-ssh._tcp</type>
     <port>22</port>
   </service>
 </service-group>
EOF

	echo "info: uninstall all flatpaks" 
	flatpak uninstall --all --assumeyes --noninteractive
	
        touch /$VSTATE/nouserlist
	
	test -e /usr/local/sbin/ltsp-org-updater && /usr/local/sbin/ltsp-org-updater --install
    fi
    
    echo "done"

    touch /$VSTATE/installed
fi

#init: runs on ervery start
if test -f /$VSTATE/installed;then
    echo -n "running ltsp-allinone-init ..."

    . /$VSTATE/profile

    if test "$PROFLE" = "shared";then
	echo "laptop"
	/usr/local/lib/ltsp/laptop-update
    else
	echo "server"
    fi
else
    exit 1
fi

exit 0
