#!/bin/sh

CONFIG="/home/.config"

test -f $CONFIG/hosttype || exit 1

#setup: runs once
if ! test -f $CONFIG/installed;then
    mkdir -p $CONFIG
    
    echo "running ltsp-allinone-setup ..."
    . $CONFIG/hosttype

    if test "$HOSTTYPE" = "laptop";then

	echo " >> configure pam_mkhomedir"
	#pam_mkhomedir
	pam-auth-update --package --enable mkhomedir

	echo " >> configure dconf"
	#no updates
	cat <<EOF > /etc/dconf/db/local.d/10-no-autoupdates
[org/gnome/software]
allow-updates=false
download-updates=false
download-updates-notify=false
EOF
	dconf update

	cat <<'EOF' > /etc/profile.d/ltsp-homedir-bookmark.sh
TMP=$(mktemp)
GTK="$HOME/.config/gtk-3.0"
if test -f $GTK/bookmarks;then 
    cat $GTK/bookmarks | grep -v "ssh://${USER}@.*/home/${USER}" >  $TMP
else
    mkdir -p $GTK
fi
if test -f /home/.config/server;then
   . /home/.config/server
   if ping -c1 -W1 "$SERVER" 2>&1 >/dev/null;then
      ort="ssh://$USER@$SERVER/home/$USER"
      echo "$ort $USER on LTSP" >> $TMP
   fi
fi
mv $TMP $GTK/bookmarks
EOF

    else
	/usr/local/sbin/ltsp-org-updater --install
    fi

    echo "done"

    touch $CONFIG/installed
fi

#init: runs on ervery start
if test -f $CONFIG/installed;then
    echo -n "running ltsp-allinone-init ..."

    . $CONFIG/hosttype

    if test "$HOSTTYPE" = "laptop";then
	echo "laptop"
	/usr/local/lib/ltsp/laptop-update
    else
	echo "server"
    fi
else
    exit 1
fi

exit 0
